apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nexus.gpte.opentlc.com
spec:
  group: gpte.opentlc.com
  names:
    kind: Nexus
    listKind: NexusList
    plural: nexus
    singular: nexus
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
